name: testarcore
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-400.0.dev <4.0.0'

dependencies:
  arcore_flutter_plugin: ^0.2.0-alpha
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/porche/scene.gltf
    - assets/models/free_1975_porsche_911_930_turbo.glb
    - assets/models/free_animals_-_quirky_series.glb
