name: testarcore
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-400.0.dev <4.0.0'

dependencies:
  arcore_flutter_plugin: any
  vector_math: any
  path_provider: any
  http: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/
